# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trn_infomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('value', models.TextField(verbose_name='本文')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('infomation_division', models.CharField(choices=[('01', '通常'), ('02', '重要')], max_length=2, verbose_name='重要度')),
            ],
        ),
    ]
